first new test

diff --git a/.github/workflows/test-pipeline.yml b/.github/workflows/test-pipeline.yml
--- a/.github/workflows/test-pipeline.yml
+++ b/.github/workflows/test-pipeline.yml
@@ -46,25 +46,32 @@ jobs:
         sudo apt-get update
         sudo apt-get install libcurl4-openssl-dev
 
-    - uses: r-lib/actions/setup-r@master
-      with:
-        r-version: ${{ matrix.r }}
+    - name: Install package
+      run: python -m pip install .
 
-    - name: Install R dependancies
-      run: Rscript scripts/installRdeps.R
+    - name: Run pytest tests
+      run: pytest tests -x -vv
 
-    - name: Run pipeline
-      run: looper run -p local tests/data/bedstat_config.yaml
 
-    - name: Test plots exist
-      run: |
-        if ls $GITHUB_WORKSPACE/outputs/bedstat_output/a6a08126cb6f4b1953ba0ec8675df85a/test_hg38*.png 1> /dev/null 2>&1; then
-          echo "SUCCESS";
-        else
-          echo "ERROR: files do not exist: $GITHUB_WORKSPACE/outputs/bedstat_output/a6a08126cb6f4b1953ba0ec8675df85a/test_hg38*.png";
-          exit 1
-        fi
+#    - uses: r-lib/actions/setup-r@master
+#      with:
+#        r-version: ${{ matrix.r }}
+#
+#    - name: Install R dependancies
+#      run: Rscript scripts/installRdeps.R
 
-    - name: Test record in PostgreSQL
-      run: |
-        echo "from bbconf import BedBaseConf; from bbconf.const import *; bbc = BedBaseConf('$GITHUB_WORKSPACE/tests/data/config_min.yaml'); assert bbc.bed.record_count == 1, 'Number of records in the bedfiles table not equal 1'" | python3 -
+#    - name: Run pipeline
+#      run: looper run -p local tests/data/bedstat_config.yaml
+#
+#    - name: Test plots exist
+#      run: |
+#        if ls $GITHUB_WORKSPACE/outputs/bedstat_output/a6a08126cb6f4b1953ba0ec8675df85a/test_hg38*.png 1> /dev/null 2>&1; then
+#          echo "SUCCESS";
+#        else
+#          echo "ERROR: files do not exist: $GITHUB_WORKSPACE/outputs/bedstat_output/a6a08126cb6f4b1953ba0ec8675df85a/test_hg38*.png";
+#          exit 1
+#        fi
+
+#    - name: Test record in PostgreSQL
+#      run: |
+#        echo "from bbconf import BedBaseConf; from bbconf.const import *; bbc = BedBaseConf('$GITHUB_WORKSPACE/tests/data/config_min.yaml'); assert bbc.bed.record_count == 1, 'Number of records in the bedfiles table not equal 1'" | python3 -
